# Define Local path
LOCAL_PATH := device/samsung/j2lte

# Vendorname
BOARD_VENDOR := samsung

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7

# Platform
TARGET_BOARD_PLATFORM := exynos3
TARGET_SLSI_VARIANT := cm
TARGET_SOC := exynos3475

# Graphics
USE_OPENGL_RENDERER := true
BOARD_EGL_CFG := device/samsung/j2lte/egl/egl.cfg

# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := universal3475

#Kernel
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_BOARD := SYSMAGIC000K 	
BOARD_KERNEL_PAGESIZE := 2048

BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --dt device/samsung/j2lte/dtb.img

# Kernel
TARGET_KERNEL_CONFIG := j2lte_00_defconfig
TARGET_KERNEL_SOURCE := kernel/samsung/j2lte

# CMHW
BOARD_HARDWARE_CLASS := device/samsung/j2lte/cmhw
# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/samsung/j2lte/bluetooth

#Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x360000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x360000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x30000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x130000000
BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/rootdir/etc/fstab.universal3475
TARGET_OTA_ASSERT_DEVICE := j2lte,j2ltedd

# PowerHAL
TARGET_POWERHAL_VARIANT := exynos3

# Sensors
TARGET_PROVIDES_LIBSENSORS := true

# GUI
BOARD_EGL_NEEDS_HANDLE_VALUE := true

# Recovery
TARGET_RECOVERY_DEVICE_DIRS += device/samsung/j2lte
TARGET_RECOVERY_FSTAB := device/samsung/j2lte/rootdir/etc/fstab.universal3475
BOARD_HAS_LARGE_FILESYSTEM := true

# TWRP
#ifeq ($(TARGET_BUILD_VARIANT),userdebug)
#RECOVERY_VARIANT := twrp
#endif

RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
TW_NO_SCREEN_BLANK := true
TW_NO_REBOOT_BOOTLOADER := true
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_CRYPTO := true
#TW_USE_TOOLBOX := true
TWRP_INCLUDE_LOGCAT := true

# Include path
TARGET_SPECIFIC_HEADER_PATH := $(LOCAL_PATH)/include
